"""Beam-style controller for verifier-backed proof-action search."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from rich.console import Console

from .proof_env import execute_action
from .proof_graph import (
    apply_trace_to_graph,
    build_graph_from_obligations,
    graph_summary,
    node_to_obligation,
    open_nodes,
    write_graph_json,
    write_graph_markdown,
)
from .proof_policy import open_obligations, propose_actions
from .proof_policy_model import load_policy_model, rerank_actions_with_value_model
from .proof_trace import ProofTrace, write_traces


def _rank_actions(
    obligation: dict[str, Any],
    beam_size: int,
    value_model_bundle: dict[str, Any] | None = None,
) -> list:
    actions = propose_actions(obligation, beam_size=beam_size)
    if value_model_bundle is not None:
        actions = rerank_actions_with_value_model(value_model_bundle, obligation, actions)
    return actions[:beam_size]


def run_controller(
    obligations_report: dict[str, Any],
    beam_size: int = 5,
    rounds: int = 1,
    value_model_bundle: dict[str, Any] | None = None,
) -> tuple[dict[str, Any], list[ProofTrace]]:
    """Run a bounded proof-action controller.

    v1 does not mutate the obligation report in-place; it records every exact
    action result and reports which child obligations were generated for future
    rounds.
    """

    traces: list[ProofTrace] = []
    frontier = open_obligations(obligations_report)
    generated_children: list[dict[str, Any]] = []
    for round_index in range(rounds):
        next_frontier: list[dict[str, Any]] = []
        for obligation in frontier:
            actions = _rank_actions(obligation, beam_size=beam_size, value_model_bundle=value_model_bundle)
            for action in actions:
                result = execute_action(action, obligation)
                trace = ProofTrace(
                    obligation_id=str(obligation.get("obligation_id")),
                    obligation_before=obligation,
                    action=action,
                    result=result,
                )
                traces.append(trace)
                children = result.details.get("children") or result.details.get("split", {}).get("children", [])
                for child in children:
                    generated_children.append(child)
                    next_frontier.append(
                        {
                            "obligation_id": child.get("obligation_id", "child"),
                            "scc_status": child.get("status", "NEEDS_SPLIT"),
                            "scope": child.get("scope", "generated child"),
                            "coverage": child.get("coverage", {}),
                            "transition_rule": child.get("transition_rule", "generated by split"),
                            "ancestor_descent": False,
                        }
                    )
        frontier = next_frontier
        if not frontier:
            break
    closed_results = sum(1 for trace in traces if trace.result.status == "CLOSED")
    reduced_results = sum(1 for trace in traces if trace.result.status == "REDUCED")
    return {
        "status": "PROOF_CONTROLLER_SCAFFOLD",
        "rounds_requested": rounds,
        "rounds_completed": 0 if not traces else round_index + 1,
        "beam_size": beam_size,
        "policy": "value_model_reranked" if value_model_bundle is not None else "heuristic_seed_policy",
        "initial_open_obligations": obligations_report.get("open_obligation_count", len(open_obligations(obligations_report))),
        "actions_tried": len(traces),
        "closed_results": closed_results,
        "reduced_results": reduced_results,
        "generated_child_obligations": len(generated_children),
        "model_guided_obligation_closure_rate": 0.0,
        "generated_children_sample": generated_children[:50],
    }, traces


def run_fixed_point_controller(
    obligations_report: dict[str, Any],
    beam_size: int = 16,
    max_rounds: int = 100,
    value_model_bundle: dict[str, Any] | None = None,
) -> tuple[dict[str, Any], list[ProofTrace], dict[str, Any]]:
    """Run proof actions until the persistent graph reaches a fixed point.

    The fixed point here is operational, not mathematical: either no graph nodes
    remain open, ``max_rounds`` is reached, or every proposed action for every
    open node has already been tried without creating new graph structure.
    """

    if max_rounds < 0:
        raise ValueError("max_rounds must be non-negative")
    graph = build_graph_from_obligations(obligations_report)
    traces: list[ProofTrace] = []
    attempted: set[tuple[str, str]] = set()
    generated_child_count = 0
    closed_direct_count = 0
    rounds_completed = 0

    for round_index in range(max_rounds):
        rounds_completed = round_index + 1
        round_traces = 0
        nodes_snapshot = list(open_nodes(graph))
        if not nodes_snapshot:
            break
        for node in nodes_snapshot:
            obligation = node_to_obligation(node)
            actions = _rank_actions(obligation, beam_size=beam_size, value_model_bundle=value_model_bundle)
            for action in actions:
                key = (node["obligation_id"], action.to_json())
                if key in attempted:
                    continue
                attempted.add(key)
                before_nodes = len(graph["nodes"])
                result = execute_action(action, obligation)
                trace = ProofTrace(
                    obligation_id=str(node["obligation_id"]),
                    obligation_before=obligation,
                    action=action,
                    result=result,
                )
                traces.append(trace)
                round_traces += 1
                apply_trace_to_graph(graph, trace)
                generated_child_count += max(0, len(graph["nodes"]) - before_nodes)
                if result.status == "CLOSED":
                    closed_direct_count += 1
        if round_traces == 0:
            break

    summary = graph_summary(graph)
    report = {
        "status": "PROOF_CONTROLLER_FIXED_POINT",
        "proof_graph_status": graph["status"],
        "rounds_requested": max_rounds,
        "rounds_completed": rounds_completed,
        "beam_size": beam_size,
        "policy": "value_model_reranked" if value_model_bundle is not None else "heuristic_seed_policy",
        "initial_open_obligations": obligations_report.get(
            "open_obligation_count",
            len(open_obligations(obligations_report)),
        ),
        "actions_tried": len(traces),
        "attempted_action_keys": len(attempted),
        "closed_direct_results": closed_direct_count,
        "generated_child_obligations": generated_child_count,
        "graph_summary": summary,
        "model_guided_obligation_closure_rate": 0.0,
        "interpretation": (
            "Fixed-point mode persists reductions into a proof graph. REDUCED actions "
            "do not close parents; parents close only by exact certificates or when all "
            "child obligations close."
        ),
    }
    return report, traces, graph


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Run bounded proof-action beam controller.")
    parser.add_argument("--obligations", required=True)
    parser.add_argument("--beam-size", type=int, default=5)
    parser.add_argument("--rounds", type=int, default=1)
    parser.add_argument("--mode", choices=["once", "fixed-point"], default="once")
    parser.add_argument("--max-rounds", type=int, default=None)
    parser.add_argument("--policy-model", default=None)
    parser.add_argument("--graph-out", default=None)
    parser.add_argument("--graph-md", default=None)
    parser.add_argument("--trace-out", required=True)
    parser.add_argument("--out", default=None)
    return parser


def main(argv: list[str] | None = None) -> None:
    args = build_arg_parser().parse_args(argv)
    obligations = json.loads(Path(args.obligations).read_text(encoding="utf-8"))
    value_model_bundle = load_policy_model(args.policy_model) if args.policy_model else None
    if args.mode == "fixed-point":
        report, traces, graph = run_fixed_point_controller(
            obligations,
            beam_size=args.beam_size,
            max_rounds=args.max_rounds if args.max_rounds is not None else args.rounds,
            value_model_bundle=value_model_bundle,
        )
        if args.graph_out:
            write_graph_json(graph, args.graph_out)
            write_graph_markdown(graph, args.graph_md or Path(args.graph_out).with_suffix(".md"))
    else:
        report, traces = run_controller(
            obligations,
            beam_size=args.beam_size,
            rounds=args.rounds,
            value_model_bundle=value_model_bundle,
        )
    out = Path(args.out or "reports/proof_controller_fixed_point.json")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    write_traces(args.trace_out, traces)
    Console().print(
        {
            "out": str(out),
            "actions": report["actions_tried"],
            "children": report["generated_child_obligations"],
            "mode": args.mode,
        }
    )


if __name__ == "__main__":
    main()
